### PR TITLE
Clients function return socketId and userId

### PR DESCRIPTION
**Pull request by Tollman**
If sockets use authentication clients function return object with keys socketId and userId.
If sockets don't use authentication - only socketId key will be present.

### CODE REVIEW

**Comment by Tollman** [comment]
I need something like this to know what exactly user in this room. This is very useful when use multi nodes. Can You implement this?

**Comment by darrachequesne** [comment]
@Tollman hi! Thanks for the PR, but I'm afraid it's out of the scope of the library.

You can save the association `socket.id <=> your userId` in some shared database, like `Redis` or `memcached` for example.

**Comment by Tollman** [comment]
@darrachequesne thanks for the answer I'll think about this.

**Comment by darrachequesne** [comment]
Closing now, please reopen if needed.

**Pull request closed without merging**
