### PR TITLE
Use a Room class to efficiently track room size.

### PR DESCRIPTION
**Pull request by manubb**
Performance improvement in room management. This follows pull request #29.

### CODE REVIEW

**Comment by kapouer** [comment]
Hello @rauchg, do you think this has a chance to get accepted ?

**Comment by nkzawa** [comment]
Thanks! Do you have any benchmark results ?
btw maybe Room class implementation can be replaced by `Map` since it has `size` property.

**Comment by kapouer** [comment]
I don't. This PR should be rewritten cleanly along with benchmarks, indeed.

**Comment by rauchg** [comment]
I'm pretty sure the new way will be faster? `Object.keys().length` should be costly.

**Comment by kapouer** [comment]
I'm in favor of using `Map` too. This PR was written when using nodejs 0.10...

**Comment by rauchg** [comment]
This looks really great @kapouer. Merged. @darrachequesne we are still planning on ES6 `Map`

**Pull request merged**
